networks:
  my-networks:
    driver: bridge

services:

  front:
    build: ./frontend/
    ports:
      - 8081:80
    environment:
      REACT_APP_API_URL: ${REACT_APP_API_URL}
    networks:
      - my-networks

  postgres:
    container_name: pg_db
    image: postgres:13.22
    restart: always
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - 5432:5432
    networks:
      - my-networks

  app:
    build: ./auth/
    ports:
      - 8080:8080
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      NAME_CONTAINER_DB: ${NAME_CONTAINER_DB}
    depends_on:
      - postgres
    networks:
      - my-networks

